name: storysaz
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.5.1
  screenshot: ^3.0.0
  image_gallery_saver: ^2.0.3
  ionicons: ^0.2.2
  iconly: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/backgrounds/

  fonts:
    - family: Estedad
      fonts:
        - asset: assets/fonts/Estedad-FD-Regular.ttf
          weight: 400
        - asset: assets/fonts/Estedad-FD-Medium.ttf
          weight: 500
        - asset: assets/fonts/Estedad-FD-SemiBold.ttf
          weight: 600
