name: storysaz
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.5.1
  screenshot: ^3.0.0
  image_gallery_saver: ^2.0.3
  ionicons: ^0.2.2
  iconly: ^1.0.1
  permission_handler: ^12.0.0+1
  app_settings: ^6.1.1
  file_picker: ^6.1.1
  indexed: ^0.0.8
  path_provider: ^2.1.3
  video_player: ^2.10.0
  video_compress: ^3.1.2
  video_thumbnail: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/backgrounds/

  fonts:
    - family: Estedad
      fonts:
        - asset: assets/fonts/Estedad-FD-Regular.ttf
          weight: 400
        - asset: assets/fonts/Estedad-FD-Medium.ttf
          weight: 500
        - asset: assets/fonts/Estedad-FD-SemiBold.ttf
          weight: 600

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/storysaz-icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
